-- Bundled TBC raid creature table. Pure data, no logic.
--
-- AUTO GENERATED. Regenerate with:
--   luajit scripts/generate-mobs.lua <Questie tbcNpcDB.lua> <this file>
--
-- Names and ids come from Questie's TBC creature database, which ships for the
-- same client this addon targets, so every name is the name the game reports.
-- Raid membership is established from spawn data where it exists, from another
-- addon's roster where a raid summons its creatures, and from a contiguous id
-- block where neither is available. See the generator for which applies where.
--
-- This table only feeds the search box. A mob missing from it can still be
-- ruled by typing its name, so a gap costs a suggestion and nothing more.
local MFD = _G.MarkedForDeath or {}

MFD.Data = MFD.Data or {}

-- [npcID] = { name, instanceKey }
MFD.Data.Mobs = {

    -- Karazhan (59)
    [15547] = { "Spectral Charger", "KARAZHAN" },
    [15548] = { "Spectral Stallion", "KARAZHAN" },
    [15550] = { "Attumen the Huntsman", "KARAZHAN" },
    [15551] = { "Spectral Stable Hand", "KARAZHAN" },
    [15687] = { "Moroes", "KARAZHAN" },
    [15688] = { "Terestian Illhoof", "KARAZHAN" },
    [15689] = { "Netherspite", "KARAZHAN" },
    [15690] = { "Prince Malchezaar", "KARAZHAN" },
    [15691] = { "The Curator", "KARAZHAN" },
    [16170] = { "Coldmist Stalker", "KARAZHAN" },
    [16171] = { "Coldmist Widow", "KARAZHAN" },
    [16173] = { "Shadowbat", "KARAZHAN" },
    [16174] = { "Greater Shadowbat", "KARAZHAN" },
    [16175] = { "Vampiric Shadowbat", "KARAZHAN" },
    [16176] = { "Shadowbeast", "KARAZHAN" },
    [16177] = { "Dreadbeast", "KARAZHAN" },
    [16178] = { "Phase Hound", "KARAZHAN" },
    [16389] = { "Spectral Apprentice", "KARAZHAN" },
    [16406] = { "Phantom Attendant", "KARAZHAN" },
    [16407] = { "Spectral Servant", "KARAZHAN" },
    [16408] = { "Phantom Valet", "KARAZHAN" },
    [16409] = { "Phantom Guest", "KARAZHAN" },
    [16410] = { "Spectral Retainer", "KARAZHAN" },
    [16411] = { "Spectral Chef", "KARAZHAN" },
    [16412] = { "Ghostly Baker", "KARAZHAN" },
    [16414] = { "Ghostly Steward", "KARAZHAN" },
    [16415] = { "Skeletal Waiter", "KARAZHAN" },
    [16424] = { "Spectral Sentry", "KARAZHAN" },
    [16425] = { "Phantom Guardsman", "KARAZHAN" },
    [16457] = { "Maiden of Virtue", "KARAZHAN" },
    [16459] = { "Wanton Hostess", "KARAZHAN" },
    [16460] = { "Night Mistress", "KARAZHAN" },
    [16461] = { "Concubine", "KARAZHAN" },
    [16468] = { "Spectral Patron", "KARAZHAN" },
    [16470] = { "Ghostly Philanthropist", "KARAZHAN" },
    [16471] = { "Skeletal Usher", "KARAZHAN" },
    [16472] = { "Phantom Stagehand", "KARAZHAN" },
    [16473] = { "Spectral Performer", "KARAZHAN" },
    [16481] = { "Ghastly Haunt", "KARAZHAN" },
    [16482] = { "Trapped Soul", "KARAZHAN" },
    [16485] = { "Arcane Watchman", "KARAZHAN" },
    [16488] = { "Arcane Anomaly", "KARAZHAN" },
    [16489] = { "Chaotic Sentience", "KARAZHAN" },
    [16491] = { "Mana Feeder", "KARAZHAN" },
    [16492] = { "Syphoner", "KARAZHAN" },
    [16504] = { "Arcane Protector", "KARAZHAN" },
    [16524] = { "Shade of Aran", "KARAZHAN" },
    [16525] = { "Spell Shade", "KARAZHAN" },
    [16526] = { "Sorcerous Shade", "KARAZHAN" },
    [16529] = { "Magical Horror", "KARAZHAN" },
    [16530] = { "Mana Warp", "KARAZHAN" },
    [16539] = { "Homunculus", "KARAZHAN" },
    [16540] = { "Shadow Pillager", "KARAZHAN" },
    [16544] = { "Ethereal Thief", "KARAZHAN" },
    [16545] = { "Ethereal Spellfilcher", "KARAZHAN" },
    [16595] = { "Fleshbeast", "KARAZHAN" },
    [16596] = { "Greater Fleshbeast", "KARAZHAN" },
    [17161] = { "Blizzard (Shade of Aran)", "KARAZHAN" },
    [17225] = { "Nightbane", "KARAZHAN" },

    -- Gruul's Lair (8)
    [18831] = { "High King Maulgar", "GRUUL" },
    [18832] = { "Krosh Firehand", "GRUUL" },
    [18834] = { "Olm the Summoner", "GRUUL" },
    [18835] = { "Kiggler the Crazed", "GRUUL" },
    [18836] = { "Blindeye the Seer", "GRUUL" },
    [19044] = { "Gruul the Dragonkiller", "GRUUL" },
    [19389] = { "Lair Brute", "GRUUL" },
    [21350] = { "Gronn-Priest", "GRUUL" },

    -- Magtheridon's Lair (3)
    [17256] = { "Hellfire Channeler", "MAGTHERIDON" },
    [17257] = { "Magtheridon", "MAGTHERIDON" },
    [18829] = { "Hellfire Warder", "MAGTHERIDON" },

    -- Serpentshrine Cavern (32)
    [21212] = { "Lady Vashj", "SERPENTSHRINE" },
    [21213] = { "Morogrim Tidewalker", "SERPENTSHRINE" },
    [21214] = { "Fathom-Lord Karathress", "SERPENTSHRINE" },
    [21215] = { "Leotheras the Blind", "SERPENTSHRINE" },
    [21216] = { "Hydross the Unstable", "SERPENTSHRINE" },
    [21217] = { "The Lurker Below", "SERPENTSHRINE" },
    [21218] = { "Vashj'ir Honor Guard", "SERPENTSHRINE" },
    [21220] = { "Coilfang Priestess", "SERPENTSHRINE" },
    [21221] = { "Coilfang Beast-Tamer", "SERPENTSHRINE" },
    [21224] = { "Tidewalker Depth-Seer", "SERPENTSHRINE" },
    [21225] = { "Tidewalker Warrior", "SERPENTSHRINE" },
    [21226] = { "Tidewalker Shaman", "SERPENTSHRINE" },
    [21227] = { "Tidewalker Harpooner", "SERPENTSHRINE" },
    [21228] = { "Tidewalker Hydromancer", "SERPENTSHRINE" },
    [21229] = { "Greyheart Tidecaller", "SERPENTSHRINE" },
    [21230] = { "Greyheart Nether-Mage", "SERPENTSHRINE" },
    [21231] = { "Greyheart Shield-Bearer", "SERPENTSHRINE" },
    [21232] = { "Greyheart Skulker", "SERPENTSHRINE" },
    [21246] = { "Serpentshrine Sporebat", "SERPENTSHRINE" },
    [21251] = { "Underbog Colossus", "SERPENTSHRINE" },
    [21263] = { "Greyheart Technician", "SERPENTSHRINE" },
    [21298] = { "Coilfang Serpentguard", "SERPENTSHRINE" },
    [21299] = { "Coilfang Fathom-Witch", "SERPENTSHRINE" },
    [21301] = { "Coilfang Shatterer", "SERPENTSHRINE" },
    [21339] = { "Coilfang Hate-Screamer", "SERPENTSHRINE" },
    [21689] = { "Coilfang Frenzy Corpse", "SERPENTSHRINE" },
    [21806] = { "Greyheart Spellbinder", "SERPENTSHRINE" },
    [21863] = { "Serpentshrine Lurker", "SERPENTSHRINE" },
    [21934] = { "Hydross Cleansing Field Helper", "SERPENTSHRINE" },
    [21964] = { "Fathom-Guard Caribdis", "SERPENTSHRINE" },
    [21965] = { "Fathom-Guard Tidalvess", "SERPENTSHRINE" },
    [21966] = { "Fathom-Guard Sharkkis", "SERPENTSHRINE" },

    -- Tempest Keep (35)
    [18805] = { "High Astromancer Solarian", "TEMPESTKEEP" },
    [19514] = { "Al'ar", "TEMPESTKEEP" },
    [19516] = { "Void Reaver", "TEMPESTKEEP" },
    [19622] = { "Kael'thas Sunstrider", "TEMPESTKEEP" },
    [20031] = { "Bloodwarder Legionnaire", "TEMPESTKEEP" },
    [20032] = { "Bloodwarder Vindicator", "TEMPESTKEEP" },
    [20033] = { "Astromancer", "TEMPESTKEEP" },
    [20034] = { "Star Scryer", "TEMPESTKEEP" },
    [20035] = { "Bloodwarder Marshal", "TEMPESTKEEP" },
    [20036] = { "Bloodwarder Squire", "TEMPESTKEEP" },
    [20037] = { "Tempest Falconer", "TEMPESTKEEP" },
    [20038] = { "Phoenix-Hawk Hatchling", "TEMPESTKEEP" },
    [20039] = { "Phoenix-Hawk", "TEMPESTKEEP" },
    [20040] = { "Crystalcore Devastator", "TEMPESTKEEP" },
    [20041] = { "Crystalcore Sentinel", "TEMPESTKEEP" },
    [20042] = { "Tempest-Smith", "TEMPESTKEEP" },
    [20043] = { "Apprentice Star Scryer", "TEMPESTKEEP" },
    [20044] = { "Novice Astromancer", "TEMPESTKEEP" },
    [20045] = { "Nether Scryer", "TEMPESTKEEP" },
    [20046] = { "Astromancer Lord", "TEMPESTKEEP" },
    [20047] = { "Crimson Hand Battle Mage", "TEMPESTKEEP" },
    [20048] = { "Crimson Hand Centurion", "TEMPESTKEEP" },
    [20049] = { "Crimson Hand Blood Knight", "TEMPESTKEEP" },
    [20050] = { "Crimson Hand Inquisitor", "TEMPESTKEEP" },
    [20051] = { "UNUSED - Golem Crafter", "TEMPESTKEEP" },
    [20052] = { "Crystalcore Mechanic", "TEMPESTKEEP" },
    [20059] = { "Sunseeker Netherbinder", "TEMPESTKEEP" },
    [20060] = { "Lord Sanguinar", "TEMPESTKEEP" },
    [20061] = { "Frostbite Invisible Stalker", "TEMPESTKEEP" },
    [20062] = { "Grand Astromancer Capernian", "TEMPESTKEEP" },
    [20063] = { "Master Engineer Telonicus", "TEMPESTKEEP" },
    [20064] = { "Thaladred the Darkener", "TEMPESTKEEP" },
    [20075] = { "Darkwater Crocolisk", "TEMPESTKEEP" },
    [20078] = { "Summoned Bloodwarder Reservist", "TEMPESTKEEP" },
    [20083] = { "Summoned Bloodwarder Mender", "TEMPESTKEEP" },

    -- Hyjal Summit (19)
    [17767] = { "Rage Winterchill", "HYJAL" },
    [17808] = { "Anetheron", "HYJAL" },
    [17818] = { "Towering Infernal", "HYJAL" },
    [17842] = { "Azgalor", "HYJAL" },
    [17864] = { "Lesser Doomguard", "HYJAL" },
    [17888] = { "Kaz'rogal", "HYJAL" },
    [17895] = { "Ghoul", "HYJAL" },
    [17897] = { "Crypt Fiend", "HYJAL" },
    [17898] = { "Abomination", "HYJAL" },
    [17899] = { "Shadowy Necromancer", "HYJAL" },
    [17902] = { "Skeleton Invader", "HYJAL" },
    [17903] = { "Skeleton Mage", "HYJAL" },
    [17905] = { "Banshee", "HYJAL" },
    [17906] = { "Gargoyle", "HYJAL" },
    [17907] = { "Frost Wyrm", "HYJAL" },
    [17908] = { "Giant Infernal", "HYJAL" },
    [17916] = { "Fel Stalker", "HYJAL" },
    [17967] = { "Crypt Scarab", "HYJAL" },
    [17968] = { "Archimonde", "HYJAL" },

    -- Black Temple (77)
    [22841] = { "Shade of Akama", "BLACKTEMPLE" },
    [22844] = { "Ashtongue Battlelord", "BLACKTEMPLE" },
    [22845] = { "Ashtongue Mystic", "BLACKTEMPLE" },
    [22846] = { "Ashtongue Stormcaller", "BLACKTEMPLE" },
    [22847] = { "Ashtongue Primalist", "BLACKTEMPLE" },
    [22848] = { "Storm Fury", "BLACKTEMPLE" },
    [22849] = { "Ashtongue Feral Spirit", "BLACKTEMPLE" },
    [22853] = { "Illidari Defiler", "BLACKTEMPLE" },
    [22855] = { "Illidari Nightlord", "BLACKTEMPLE" },
    [22856] = { "Reliquary of the Lost", "BLACKTEMPLE" },
    [22869] = { "Illidari Boneslicer", "BLACKTEMPLE" },
    [22871] = { "Teron Gorefiend", "BLACKTEMPLE" },
    [22873] = { "Coilskar General", "BLACKTEMPLE" },
    [22874] = { "Coilskar Harpooner", "BLACKTEMPLE" },
    [22875] = { "Coilskar Sea-Caller", "BLACKTEMPLE" },
    [22876] = { "Coilskar Soothsayer", "BLACKTEMPLE" },
    [22877] = { "Coilskar Wrangler", "BLACKTEMPLE" },
    [22878] = { "Aqueous Lord", "BLACKTEMPLE" },
    [22879] = { "Shadowmoon Reaver", "BLACKTEMPLE" },
    [22880] = { "Shadowmoon Champion", "BLACKTEMPLE" },
    [22882] = { "Shadowmoon Deathshaper", "BLACKTEMPLE" },
    [22883] = { "Aqueous Spawn", "BLACKTEMPLE" },
    [22884] = { "Leviathan", "BLACKTEMPLE" },
    [22885] = { "Dragon Turtle", "BLACKTEMPLE" },
    [22887] = { "High Warlord Naj'entus", "BLACKTEMPLE" },
    [22898] = { "Supremus", "BLACKTEMPLE" },
    [22917] = { "Illidan Stormrage", "BLACKTEMPLE" },
    [22939] = { "Temple Concubine", "BLACKTEMPLE" },
    [22945] = { "Shadowmoon Blood Mage", "BLACKTEMPLE" },
    [22946] = { "Shadowmoon War Hound", "BLACKTEMPLE" },
    [22947] = { "Mother Shahraz", "BLACKTEMPLE" },
    [22948] = { "Gurtogg Bloodboil", "BLACKTEMPLE" },
    [22949] = { "Gathios the Shatterer", "BLACKTEMPLE" },
    [22950] = { "High Nethermancer Zerevor", "BLACKTEMPLE" },
    [22951] = { "Lady Malande", "BLACKTEMPLE" },
    [22952] = { "Veras Darkshadow", "BLACKTEMPLE" },
    [22953] = { "Wrathbone Flayer", "BLACKTEMPLE" },
    [22954] = { "Illidari Fearbringer", "BLACKTEMPLE" },
    [22955] = { "Charming Courtesan", "BLACKTEMPLE" },
    [22956] = { "Sister of Pain", "BLACKTEMPLE" },
    [22957] = { "Priestess of Dementia", "BLACKTEMPLE" },
    [22959] = { "Spellbound Attendant", "BLACKTEMPLE" },
    [22960] = { "Dragonmaw Wyrmcaller", "BLACKTEMPLE" },
    [22962] = { "Priestess of Delight", "BLACKTEMPLE" },
    [22963] = { "Bonechewer Worker", "BLACKTEMPLE" },
    [22964] = { "Sister of Pleasure", "BLACKTEMPLE" },
    [22965] = { "Enslaved Servant", "BLACKTEMPLE" },
    [23018] = { "Shadowmoon Houndmaster", "BLACKTEMPLE" },
    [23028] = { "Bonechewer Taskmaster", "BLACKTEMPLE" },
    [23030] = { "Dragonmaw Sky Stalker", "BLACKTEMPLE" },
    [23047] = { "Shadowmoon Soldier", "BLACKTEMPLE" },
    [23049] = { "Shadowmoon Weapon Master", "BLACKTEMPLE" },
    [23147] = { "Shadowmoon Grunt", "BLACKTEMPLE" },
    [23172] = { "Hand of Gorefiend", "BLACKTEMPLE" },
    [23196] = { "Bonechewer Behemoth", "BLACKTEMPLE" },
    [23222] = { "Bonechewer Brawler", "BLACKTEMPLE" },
    [23223] = { "Bonechewer Spectator", "BLACKTEMPLE" },
    [23232] = { "Mutant War Hound", "BLACKTEMPLE" },
    [23235] = { "Bonechewer Blade Fury", "BLACKTEMPLE" },
    [23236] = { "Bonechewer Shield Disciple", "BLACKTEMPLE" },
    [23237] = { "Bonechewer Blood Prophet", "BLACKTEMPLE" },
    [23239] = { "Bonechewer Combatant", "BLACKTEMPLE" },
    [23330] = { "Dragonmaw Wind Reaver", "BLACKTEMPLE" },
    [23337] = { "Illidari Centurion", "BLACKTEMPLE" },
    [23339] = { "Illidari Heartseeker", "BLACKTEMPLE" },
    [23374] = { "Ashtongue Stalker", "BLACKTEMPLE" },
    [23394] = { "Promenade Sentinel", "BLACKTEMPLE" },
    [23397] = { "Illidari Blood Lord", "BLACKTEMPLE" },
    [23398] = { "Angered Soul Fragment", "BLACKTEMPLE" },
    [23399] = { "Suffering Soul Fragment", "BLACKTEMPLE" },
    [23400] = { "Illidari Archon", "BLACKTEMPLE" },
    [23401] = { "Hungering Soul Fragment", "BLACKTEMPLE" },
    [23402] = { "Illidari Battle-mage", "BLACKTEMPLE" },
    [23403] = { "Illidari Assassin", "BLACKTEMPLE" },
    [23420] = { "Essence of Anger", "BLACKTEMPLE" },
    [23421] = { "Ashtongue Channeler", "BLACKTEMPLE" },
    [23426] = { "The Illidari Council", "BLACKTEMPLE" },

    -- Zul'Aman (29)
    [23542] = { "Amani'shi Axe Thrower", "ZULAMAN" },
    [23574] = { "Akil'zon", "ZULAMAN" },
    [23576] = { "Nalorakk", "ZULAMAN" },
    [23577] = { "Halazzi", "ZULAMAN" },
    [23578] = { "Jan'alai", "ZULAMAN" },
    [23580] = { "Amani'shi Warbringer", "ZULAMAN" },
    [23581] = { "Amani'shi Medicine Man", "ZULAMAN" },
    [23582] = { "Amani'shi Tribesman", "ZULAMAN" },
    [23584] = { "Amani Bear", "ZULAMAN" },
    [23586] = { "Amani'shi Scout", "ZULAMAN" },
    [23596] = { "Amani'shi Flame Caster", "ZULAMAN" },
    [23597] = { "Amani'shi Guardian", "ZULAMAN" },
    [23774] = { "Amani'shi Trainer", "ZULAMAN" },
    [23834] = { "Amani Dragonhawk", "ZULAMAN" },
    [23863] = { "Zul'jin", "ZULAMAN" },
    [23889] = { "Amani'shi Savage", "ZULAMAN" },
    [24043] = { "Amani Lynx", "ZULAMAN" },
    [24059] = { "Amani'shi Beast Tamer", "ZULAMAN" },
    [24064] = { "Amani Lynx Cub", "ZULAMAN" },
    [24065] = { "Amani'shi Handler", "ZULAMAN" },
    [24138] = { "Tamed Amani Crocolisk", "ZULAMAN" },
    [24175] = { "Amani'shi Lookout", "ZULAMAN" },
    [24179] = { "Amani'shi Wind Walker", "ZULAMAN" },
    [24180] = { "Amani'shi Protector", "ZULAMAN" },
    [24239] = { "Hex Lord Malacrass", "ZULAMAN" },
    [24325] = { "Eagle Troll Spawn Target", "ZULAMAN" },
    [24374] = { "Amani'shi Berserker", "ZULAMAN" },
    [24530] = { "Amani Elder Lynx", "ZULAMAN" },
    [24549] = { "Amani'shi Tempest", "ZULAMAN" },

    -- Sunwell Plateau (33)
    [24850] = { "Kalecgos", "SUNWELL" },
    [24882] = { "Brutallus", "SUNWELL" },
    [25038] = { "Felmyst", "SUNWELL" },
    [25165] = { "Lady Sacrolash", "SUNWELL" },
    [25166] = { "Grand Warlock Alythess", "SUNWELL" },
    [25315] = { "Kil'jaeden", "SUNWELL" },
    [25363] = { "Sunblade Cabalist", "SUNWELL" },
    [25367] = { "Sunblade Arch Mage", "SUNWELL" },
    [25368] = { "Sunblade Slayer", "SUNWELL" },
    [25369] = { "Sunblade Vindicator", "SUNWELL" },
    [25370] = { "Sunblade Dusk Priest", "SUNWELL" },
    [25371] = { "Sunblade Dawn Priest", "SUNWELL" },
    [25372] = { "Sunblade Scout", "SUNWELL" },
    [25373] = { "Shadowsword Soulbinder", "SUNWELL" },
    [25483] = { "Shadowsword Manafiend", "SUNWELL" },
    [25484] = { "Shadowsword Assassin", "SUNWELL" },
    [25486] = { "Shadowsword Vanquisher", "SUNWELL" },
    [25506] = { "Shadowsword Lifeshaper", "SUNWELL" },
    [25507] = { "Sunblade Protector", "SUNWELL" },
    [25508] = { "Shadowsword Guardian", "SUNWELL" },
    [25509] = { "Priestess of Torment", "SUNWELL" },
    [25588] = { "Hand of the Deceiver", "SUNWELL" },
    [25591] = { "Painbringer", "SUNWELL" },
    [25592] = { "Doomfire Destroyer", "SUNWELL" },
    [25593] = { "Apocalypse Guard", "SUNWELL" },
    [25595] = { "Chaos Gazer", "SUNWELL" },
    [25597] = { "Oblivion Mage", "SUNWELL" },
    [25599] = { "Cataclysm Hound", "SUNWELL" },
    [25741] = { "M'uru", "SUNWELL" },
    [25837] = { "Shadowsword Commander", "SUNWELL" },
    [25851] = { "Volatile Fiend", "SUNWELL" },
    [25867] = { "Sunblade Dragonhawk", "SUNWELL" },
    [25953] = { "Fel Crystal Spell Target", "SUNWELL" },
}

_G.MarkedForDeath = MFD
